### ISSUE TITLE
Difference between codemod-js and jscodeshift

### ISSUE THREAD

**Issue by DanielRuf** [codemod-js/codemod#271]
What is the difference between this and https://github.com/facebook/jscodeshift?

**Comment by eventualbuddha** [comment]
The short answer: not much.

The slightly more involved answer is that jscodeshift is sort of like jQuery for ASTs. It has some built-in stuff to make more common operations easier, like renaming variables. This project more or less just uses the babel transform pipeline directly, so you write babel plugins and they modify your code the same way a build-time babel transform would but also preserves formatting etc using recast.

They both use babel and they both use recast. It really comes down to a style preference: would you rather write jQuery-style AST manipulation code or babel plugin visitor-style AST manipulation code?
