### ISSUE TITLE
Is there any way to ignore certain paths?

### ISSUE THREAD

**Issue by RIP21** [codemod-js/codemod#693]
Hi, I'm wondering if there is some way to let say in monorepo tell codemod `./packages`
But tell it to ignore `node_modules` that are, surely nested.
Right now it starts to match all the stuff.
I assume I can do that with glob pattern, but I had no success build one that is doing that :)
Suggestion what pattern will work will be greatly appreciated :) Or smth like `.codemodignore` with `node_modules` in it :)

**Comment by eventualbuddha** [comment]
There's no way to do it from the CLI, and unfortunately `@codemod/cli` doesn't expose enough to make it easy to do programmatically either. If I exposed `CLIEngine` and `ConfigBuilder` you could make a script like so to do what you want:

```ts
// This does NOT work with any released version yet.
import { CLIEngine, ConfigBuilder } from '@codemod/cli'

const config = new ConfigBuilder()
  .ignore((path: string, basename: string) => {
    // return false to ignore any path you want
  })
  .addSourcePath('./packages')
  .addLocalPlugin('my-codemod-package')
  .build()

const engine = new CLIEngine(config)
await engine.run()
```

That's probably not what you really wanted though. So instead, I just made #697 to ignore `node_modules` by default. It'll be published soon.

**Comment by eventualbuddha** [comment]
Published in `@codemod/cli` v2.2.1.

**Comment by RIP21** [comment]
Awesome, thanks :) That makes sense IMO as I can't really imagine somebody running a codemod against node_modules :) 
Prettier, babel all those are ignoring it by default AFAIR so it makes sense :) 

About a programmatic use case that would be also pretty helpful. Especially for some internal CLI tools for migrations and stuff.
Like you install `company-name-cli` and then run `company-name-cli codemod migrate-internal-lib-v4-to-v5 --dir ./my-app`
And inside you build this CLI engine and run codemod against the source dir given. 
Sounds redundant :) But on a big scale, you want it to be as easy as possible to make people actually using it :)

**Comment by eventualbuddha** [comment]
Do you have a specific example of how you'd use it? I'm happy to expose an API to make it easier.

**Comment by RIP21** [comment]
Exactly how you wrote above.

I'm developing a company wide CLI that has a lot of stuff in it, like scaffolding of libraries, apps, microfrontends and potentially other handy tools for maintaining, migration and refactorings.

And for now if we run codemod it requires few steps, installing of at least 2 dependencies, a plugin and a CLI and then running this cli with some particular flags like prettier etc. It's a simple task, but for many even reading 4-5 steps README is too much. So in order to simplify all that having it all abstracted away into a tool, like create-react-app that will install all the recommended codemods under the hood, proactively will ask what codemod person wants, then dir and all is done, will be the best thing.

So as an example.
```
cli codemod

Select codemod you want to apply:
fix-this
migrate-that
rename-that

Please provide a directory with the source files:./src

Working... ⚒ 

//Output of codemod is here
```
It's all in interactive shell like Yeoman or similar.
All defaults, like formatter, what's the plugin, or what's the options of the plugin, also can be abstracted away, or a choice can be given if it's not against our standards.

So as you can run babel or prettier, webpack programmatically running codemod the same way would be awesome. 

Hope that I explained good enough :) From the phone, so sorry if not too much details.
