### ISSUE TITLE
Suggestion: replace custom file path resolver with globby

### ISSUE THREAD

**Issue by NickHeiner** [codemod-js/codemod#770]
I see that the current file path resolver manually traverses directories, and hardcodes to exclude some directories, like `node_modules`.

I suggest using a third-party solution like [`globby`](https://www.npmjs.com/package/globby) instead. This automatically gives functionality like more sophisticated patterns, or pattern exclusions. And it reduces the amount of code in this project.

And, instead of hardcoding directories to ignore, I'd recommend reading the user's `gitignore` and just ignoring everything there.

**Comment by eventualbuddha** [comment]
Thank you for another good suggestion 😄 I agree, and would likewise be happy to review a PR or help whoever wants to get started on this. I may have time to get to this and #771, but not in the immediate future.

**Comment by NickHeiner** [comment]
Sounds good. And while I'm in here, would you mind if I submitted PRs to use other sorts of third-party libs, like using `yargs` instead of a manual args parser?

**Comment by eventualbuddha** [comment]
If there's a clear benefit to using the 3rd party libs in terms of improved functionality or reduced complexity or performance improvements or similar, and the libs are popular and maintained, then that's fine.

**Comment by eventualbuddha** [comment]
Fixed by #772, but also kinda reverted in #875.

**Comment by NickHeiner** [comment]
For what it's worth, I also addressed this in https://github.com/NickHeiner/jscodemod.
