### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by pelhage** [codemod-js/codemod#866]
Does anyone have a good debugger workflow for working with `babel-codemod`?

ASTExplorer is great, but somewhat tedious- i wish I can work more in my IDE and iterate plugin development without ASTExplorer

Ability to step through the plugin or log output would be helpful

**Comment by eventualbuddha** [comment]
When I need to do more debugging I use the built-in debugging in VS Code, which just hooks into the default `node --inspect-brk` support. I'm not sure whether it makes sense to have anything beyond that in `codemod`, though more verbose logging could be a good step in that direction.
