### ISSUE TITLE
3.1.0 Breaking Changes?

### ISSUE THREAD

**Issue by Slapbox** [codemod-js/codemod#884]
Thanks for the great work on this package!

Codemods that used to work with `2.3.2`/`3.0.1` no longer work in `3.1.0` and above. I don't see any breaking changes listed. Were there any? Or any ideas what we should investigate?

This codemod no longer works for us after the update: https://www.npmjs.com/package/import-move-codemod

**Comment by Slapbox** [comment]
I guess it's only broken on Windows (Both PowerShell and Cygwin.)

@eventualbuddha

**Comment by eventualbuddha** [comment]
The instructions in the README for `import-move-codemod` don't work because they include `--printer prettier`, and the `--printer` option was removed in `@codemod/cli@3.0.0`. I tried it with the current version without `--printer prettier` and it seemed to work.

**Comment by Slapbox** [comment]
Thanks for taking a look into this @eventualbuddha, much appreciated.

**Comment by Slapbox** [comment]
Uh actually I'm pretty sure that that wasn't the issue because I had already removed it from our command and it still failed. I thought you meant they invoked it themselves in their package, but that's not the case.

As I mentioned later, the issue only affects Windows (which wouldn't be the case if it was `--printer pretter` that was the option.

**Comment by eventualbuddha** [comment]
Can you provide some steps for reproducing the issue and the error output? Doesn't need to be too detailed.

**Comment by Slapbox** [comment]
Thanks again for your reply @eventualbuddha. All this time later I can't be certain, but the failing command likely looked something like this:

```js
yarn codemod -p import-move-codemod -o import-move-codemod=@./internals/codemods/some-codemod.json app/desktop/**/!(*browserified*).{js,ts,jsx,tsx}
```

This is a newer glob than what we were using back then, but I'm pretty certain that the glob was not to blame or in any way related - but again going by 7 month old memory.
