### ISSUE TITLE
function expression m.anything doesn't match null id

### ISSUE THREAD

**Issue by j4k0xb** [codemod-js/codemod#921]
Is it a bug that `m.functionExpression(m.anything()).match({ type: "FunctionExpression", id: null })` is `false`?
(Works as expected with `id: undefined` and `m.anything().match(null)` is true as well)

![image](https://github.com/codemod-js/codemod/assets/55899582/65be06c3-9efb-4d30-a809-b19059e7ea75)

**Comment by eventualbuddha** [comment]
Fixed in `@codemod/matchers@1.7.1`.
